version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "RahulKumar8911"
    assignees:
      - "RahulKumar8911"
    commit-message:
      prefix: "deps"
      include: "scope"
